java-world:
  min-y: -64
  max-y: 1952

bedrock-window:
  min-y: -64
  max-y: 320
  height: 384
  center: 128

triggers:
  upper: 256
  lower: 0

chunk-resend-delay-ticks: 10
debug: false
bedrock-only: true