java-world:
  min-y: -64
  max-y: 2032

bedrock-window:
  min-y: -64
  max-y: 320
  height: 384
  center: 128

triggers:
  upper: 270
  lower: -14

chunk-resend-delay-ticks: 10
debug: false
bedrock-only: true