name: BedrockHeightOffset
version: '3.0.0'
main: fr.buildtheearth.bedrockheightoffset.BedrockHeightOffset
api-version: '1.21'
authors: [ BuildTheEarth ]

depend:
  - ProtocolLib

softdepend:
  - Geyser-Spigot
  - floodgate

commands:
  bho:
    description: BedrockHeightOffset admin commands
    usage: /bho <info|reload|offset <player>|list|debug>
    permission: bho.admin

permissions:
  bho.admin:
    default: op